version: "3.8"

services:
  todo-service-database:
    image: mongo:5.0
    container_name: todo-service-database
    expose:
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - todo:/var/lib/mongodb
  todo-service-api:
    image: library/todo-service-image
    container_name: todo-service-api
    expose:
      - 8080
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - todo-service-database

  auth-service-database:
    container_name: auth-service-database
    image: library/postgres:alpine3.15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: keycloak_db
    ports:
      - "5433:5433"
    volumes:
      - todo:/var/lib/postgresql
    restart: unless-stopped

  keycloak:
    image: jboss/keycloak:16.0.0
    container_name: keycloak
    volumes:
      - ./keycloak/realm-export.json:/opt/jboss/keycloak/imports/realm-export.json
      - ./keycloak/profile.properties:/opt/jboss/keycloak/standalone/configuration/profile.properties
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: auth-service-database
      DB_DATABASE: keycloak_db
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json
    ports:
      - "8484:8080"
    depends_on:
      - auth-service-database

#  media-service-api:
#    image: library/media-service-image
#    container_name: media-service-api
#    environment:
#      S3_ACCESSKEYID: ${AWS_S3_ACCESS_KEY_ID}
#      S3_SECRETKEY: ${AWS_S3_SECRET_KEY}
#    expose:
#      - 8888
#    ports:
#      - "8888:8080"
#    restart: "no"


#  service-discovery-server:
#      image: library/service-discovery-server
#      container_name: service-discovery-server
#      expose:
#        - 8761
#      ports:
#        - "8761:8761"

volumes:
  todo: