/*
 * This file was generated by the Gradle 'init' task.
 */

pluginManagement {
    repositories {
        maven {
            name = "MyPrivateGCPRepo"
            url = uri("https://original-glyph-349716.lm.r.appspot.com/")
        }
        gradlePluginPortal()
    }
}

rootProject.name = "todo-service"
